from aiogram.types import ReplyKeyboardRemove, ReplyKeyboardMarkup, KeyboardButton, InlineKeyboardMarkup, InlineKeyboardButton

inline_cat_1 = InlineKeyboardButton('Фрукты, орехи', callback_data='cat1')
inline_cat_2 = InlineKeyboardButton('Овощи', callback_data='cat2')
inline_cat_3 = InlineKeyboardButton('Крупы', callback_data='cat3')
inline_cat_4 = InlineKeyboardButton('Мясо, молоко, яйца', callback_data='cat4')
inline_cat_5 = InlineKeyboardButton('Напитки и сладкое', callback_data='cat7')

inline_know_1 = InlineKeyboardButton('Узнать эко-цену продукта', callback_data='know1')
inline_know_2 = InlineKeyboardButton('Полный список продуктов', callback_data='know2')
inline_know_3 = InlineKeyboardButton('Больше об устойчивости', callback_data='know3')

veg_1 = InlineKeyboardButton('Помидоры', callback_data='calc Помидоры')
veg_2 = KeyboardButton('Капуста', callback_data='calc Капуста')
veg_3 = KeyboardButton('Маниока', callback_data='calc Маниока')
veg_4 = KeyboardButton('Огурцы', callback_data='calc Огурцы')
veg_5 = InlineKeyboardButton('Кукуруза', callback_data='calc Кукуруза')
veg_6 = InlineKeyboardButton('Лук', callback_data='calc Лук')
veg_7 = InlineKeyboardButton('Картофель', callback_data='calc Картофель')
veg_8 = InlineKeyboardButton('Тыква', callback_data='calc Тыква')
veg_9 = InlineKeyboardButton('Прочие корнеплоды', callback_data='calc Прочие корнеплоды')
veg_10 = InlineKeyboardButton('Другие овощи', callback_data='calc Другие овощи')

fruit_1 = InlineKeyboardButton('Яблоки', callback_data='calc Яблоки')
fruit_2 = InlineKeyboardButton('Бананы', callback_data='calc Бананы')
fruit_3 = InlineKeyboardButton('Ягоды, виноград', callback_data='calc Ягоды, виноград')
fruit_4 = InlineKeyboardButton('Персики', callback_data='calc Персики')
fruit_5 = InlineKeyboardButton('Арахис', callback_data='calc Арахис')
fruit_6 = InlineKeyboardButton('Манго', callback_data='calc Манго')
fruit_7 = InlineKeyboardButton('Апельсины', callback_data='calc Апельсины')
fruit_8 = InlineKeyboardButton('Орехи', callback_data='calc Орехи')
fruit_9 = InlineKeyboardButton('Прочие цитрусовые', callback_data='calc Прочие цитрусовые')
fruit_10 = InlineKeyboardButton('Прочие фрукты', callback_data='calc Прочие фрукты')

grain_1 = InlineKeyboardButton('Ячмень', callback_data='calc Ячмень')
grain_2 = InlineKeyboardButton('Свекольный сахар', callback_data='calc Свекольный сахар')
grain_3 = InlineKeyboardButton('Тростниковый сахар', callback_data='calc Тростниковый сахар')
grain_4 = InlineKeyboardButton('Овсянка', callback_data='calc Овсянка')
grain_5 = InlineKeyboardButton('Рис', callback_data='calc Рис')
grain_6 = InlineKeyboardButton('Пшеница и рожь', callback_data='calc Пшеница и рожь')

meat_1 = InlineKeyboardButton('Говядина', callback_data='calc Говядина')
meat_2 = InlineKeyboardButton('Баранина', callback_data='calc Баранина')
meat_3 = InlineKeyboardButton('Свинина', callback_data='calc Свинина')
meat_4 = InlineKeyboardButton('Птица', callback_data='calc Птица')
milk_1 = InlineKeyboardButton('Молоко коровье', callback_data='calc Молоко коровье')
milk_2 = InlineKeyboardButton('Яйца', callback_data='calc Яйца')
milk_3 = InlineKeyboardButton('Сыр', callback_data='calc Сыр')

drinks_1 = InlineKeyboardButton('Кофе', callback_data='calc Кофе')
drinks_2 = InlineKeyboardButton('Вино', callback_data='calc Вино')
sweet_1 = InlineKeyboardButton('Тёмный шоколад', callback_data='calc Тёмный шоколад')

inline_categories = InlineKeyboardMarkup(row_width=1).add(inline_cat_1, inline_cat_2, inline_cat_3, inline_cat_4, inline_cat_5)
inline_vegetables = InlineKeyboardMarkup(row_width=1).add(veg_1, veg_2, veg_3, veg_4, veg_5, veg_6, veg_7, veg_8, veg_9, veg_10)
inline_fruits = InlineKeyboardMarkup(row_width=1).add(fruit_1, fruit_2, fruit_3, fruit_4, fruit_5, fruit_6, fruit_7, fruit_8, fruit_9, fruit_10)
inline_grain = InlineKeyboardMarkup(row_width=1).add(grain_1, grain_2, grain_3, grain_4, grain_5, grain_6)
inline_meat = InlineKeyboardMarkup(row_width=1).add(meat_1, meat_2, meat_3, meat_4, milk_1, milk_2, milk_3)
inline_drinks = InlineKeyboardMarkup(row_width=1).add(drinks_1, drinks_2, sweet_1)
inline_knowledge = InlineKeyboardMarkup(row_width=1).add(inline_know_1, inline_know_2, inline_know_3)

veg_buttons = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True, row_width=2).add(veg_1, veg_2, veg_3, veg_4)
fruit_buttons = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True, row_width=3).add(fruit_1, fruit_2, fruit_3, fruit_4, fruit_5, fruit_6)